### ISSUE TITLE
UnboundLocalError: local variable 'previous_3D' referenced before assignment

### ISSUE THREAD

**Issue by binfenhuayun** [MediaBrain-SJTU/GroupNet#12]
previous_3D = np.reshape(previous_3D,(batch,actor_num,args.future_length, 2))
draw_result(best_guess,previous_3D)
draw_result(gt,previous_3D,mode='gt')
return 
  soft_max_1d = F.softmax(trans_input)
Traceback (most recent call last):
  File "**test_nba.py**", line 276, in <module>
    **vis_result(test_loader, args)**
  **File "test_nba.py", line 120, in vis_result**
    **previous_3D = np.reshape(previous_3D,(batch,actor_num,args.future_length, 2))**
UnboundLocalError: local variable 'previous_3D' referenced before assignment

**Comment by Vikhyat2603** [comment]
Refer to pull request https://github.com/MediaBrain-SJTU/GroupNet/pull/8
